# ==============================================================================
# YAML LINT CONFIGURATION
# ==============================================================================
# Configuration for yamllint pre-commit hook
# ==============================================================================

extends: default

rules:
  # Allow longer lines for readability in data science configs
  line-length:
    max: 120
    level: warning

  # Allow empty values in mappings (common in ML configs)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Be more lenient with comments
  comments-indentation: disable

  # Allow trailing spaces in comments
  comments:
    require-starting-space: false

  # Allow indentation that works well with Python
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
